name: Release Pull Request Manager Hub - DEV

on:
  push:
    branches: [ development, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Add nuget to PATH
        uses: nuget/setup-nuget@v1
      - name: Install TFX CLI
        run: npm i -g tfx-cli
      - name: Build
        run: npm install && npm run build
      - name: Package
        run: npm run package-dev
      - uses: actions/upload-artifact@v2
        with:
          name: "azure-pull-request-hub-dev.v${{ github.GITHUB_RUN_NUMBER }}.vsix"
          path: "${{ github.workspace }}/azure-pull-request-hub-dev.vsix"
  deploy:
    runs-on: ubuntu-latest
    environment: 'dev'
    needs: build
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: "azure-pull-request-hub-dev.v${{ github.GITHUB_RUN_NUMBER }}.vsix"
      - name: Add nuget to PATH
        uses: nuget/setup-nuget@v1
      - name: Install TFX CLI
        run: npm i -g tfx-cli
      - name: Publish Extension - DEV
        run: tfx extension publish --json --publisher ${{ vars.PUBLISHER_ID }} --vsix "azure-pull-request-hub-dev.v${{ github.GITHUB_RUN_NUMBER }}.vsix" --share-with ${{ vars.SHARE_WITH }} --auth-type ${{ secrets.ADO_TOKEN }}
