name: Release Pull Request Manager Hub - DEV

on:
  push:
    branches: [ development, main ]

env:
  extension_version_command: echo "EXTENSION_VERSION=v2.$(date +'%Y%m%d').$GITHUB_RUN_NUMBER" >> $GITHUB_ENV

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: set env
        run: ${{ env.extension_version_command }}
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Add nuget to PATH
        uses: nuget/setup-nuget@v1
      - name: Install TFX CLI
        run: npm i -g tfx-cli
      - name: Build
        run: npm install && npm run build
      - name: Package
        run: npm run package-dev
      - uses: actions/upload-artifact@v2
        with:
          name: "azure-pull-request-hub-dev.${{ env.EXTENSION_VERSION }}.vsix"
          path: "${{ github.workspace }}/azure-pull-request-hub-dev.vsix"
  deploy:
    runs-on: ubuntu-latest
    environment: 'dev'
    needs: build
    steps:
      - name: set env
        run: ${{ env.extension_version_command }}
      - uses: actions/download-artifact@v3
        with:
          name: "azure-pull-request-hub-dev.${{ env.EXTENSION_VERSION }}.vsix"
      - name: Display structure of downloaded files
        run: ls -R
      - name: Add nuget to PATH
        uses: nuget/setup-nuget@v1
      - name: Install TFX CLI
        run: npm i -g tfx-cli
      - name: Publish Extension - DEV
        run: tfx extension publish --json --publisher ${{ vars.PUBLISHER_ID }} --vsix "${{ github.workspace }}/azure-pull-request-hub-dev.vsix" --share-with ${{ vars.SHARE_WITH }} --auth-type ${{ secrets.ADO_TOKEN }}
